# Generated by Django 6.0.1 on 2026-04-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=150)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('transport_mode', models.CharField(choices=[('AIR', 'Air Freight (Germany to Ghana)'), ('SEA', 'Sea Cargo (Hamburg/Bremen to Tema)'), ('LAND', 'Land Delivery (Within Ghana)')], default='SEA', max_length=10)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received in Germany Warehouse'), ('SORTING', 'Sorting & Packaging'), ('DEPARTED', 'Departed Germany'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_GH', 'Arrived in Ghana (Tema/KIA)'), ('CLEARING', 'Customs Clearing'), ('READY', 'Ready for Collection'), ('DELIVERED', 'Delivered to Recipient')], default='RECEIVED', max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in Kilograms', max_digits=10)),
                ('description', models.TextField(blank=True, help_text="What's in the box?")),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
