# Generated by Django 6.0.1 on 2026-04-06 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Request Received'), ('RECEIVED', 'Received in Warehouse'), ('SORTING', 'Sorting & Packaging'), ('DEPARTED', 'Departed Origin'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_DEST', 'Arrived at Destination'), ('CLEARING', 'Customs Clearing'), ('READY', 'Ready for Collection'), ('DELIVERED', 'Delivered to Recipient')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='transport_mode',
            field=models.CharField(choices=[('GH_DE', 'Ghana to Germany'), ('DE_GH', 'Germany to Ghana'), ('GH_GH', 'Within Ghana (Local)'), ('DE_DE', 'Within Germany (Local)')], default='DE_GH', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in Kilograms', max_digits=10, null=True),
        ),
    ]
