# Generated by Django 6.0.1 on 2026-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipment_user_alter_shipment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(default='Origin Warehouse', help_text='Where is the cargo right now?', max_length=255),
        ),
    ]
