# Generated by Django 6.0.1 on 2026-04-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_shipment_current_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='e.g. USD, EUR, GBP', max_length=3, unique=True)),
                ('rate_to_ghs', models.DecimalField(decimal_places=4, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_message', models.TextField(blank=True, help_text='The sticky message displayed to all users.')),
                ('show_banner', models.BooleanField(default=False)),
                ('use_auto_rates', models.BooleanField(default=False, help_text='If checked, system will fetch rates from API.')),
                ('banner_color', models.CharField(choices=[('bg-blue-600', 'Info Blue'), ('bg-red-600', 'Alert Red'), ('bg-emerald-600', 'Success Green')], default='bg-blue-600', max_length=20)),
            ],
            options={
                'verbose_name': 'System Wide Control',
                'verbose_name_plural': 'System Wide Control',
            },
        ),
    ]
