# Generated by Django 6.0.1 on 2026-04-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_currencyrate_systemcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='currency_code',
            field=models.CharField(default='EUR', help_text='EUR, USD, or GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='shipment',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
