# Generated by Django 6.0.1 on 2026-04-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_shipment_currency_code_shipment_price_per_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='price_per_kg',
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Duration of journey for local routes', max_digits=5),
        ),
        migrations.AddField(
            model_name='shipment',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per KG or per Hour', max_digits=10),
        ),
    ]
