# Generated by Django 6.0.1 on 2026-04-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_remove_shipment_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_city',
            field=models.CharField(blank=True, help_text='Final city for local routes', max_length=100, null=True),
        ),
    ]
