# Generated by Django 6.0.1 on 2026-04-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_shipment_destination_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated road distance', max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
