# Generated by Django 6.0.1 on 2026-04-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_shipment_destination_address_shipment_distance_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_attempted', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('violation_type', models.CharField(choices=[('UNAUTHORIZED_ACCESS', 'Access Denied (Non-Staff)'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('BRUTE_FORCE_SIGNUP', 'Suspicious Signup Activity')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='currency_code',
            field=models.CharField(help_text='e.g. USD, GHS, GBP', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='rate_to_ghs',
            field=models.DecimalField(decimal_places=4, help_text='How many of this currency equals 1 EUR?', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='currency_code',
            field=models.CharField(default='EUR', help_text='EUR, USD, GBP, or GHS', max_length=3),
        ),
    ]
