# Generated by Django 6.0.1 on 2026-04-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_violationlog_alter_currencyrate_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationlog',
            name='violation_type',
            field=models.CharField(choices=[('UNAUTHORIZED_ACCESS', 'Access Denied (Non-Staff)'), ('UNAUTHORIZED_ADMIN_ATTEMPT', 'Unauthorized Admin Terminal Attempt'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('BRUTE_FORCE_SIGNUP', 'Suspicious Signup Activity')], max_length=50),
        ),
    ]
