# Generated by Django 6.0.1 on 2026-04-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0010_alter_violationlog_violation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcontrol',
            name='default_price_per_hr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Global price for local land routes per Hour', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='default_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Global price for international routes per KG', max_digits=10),
        ),
    ]
