# Generated by Django 6.0.1 on 2026-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_systemcontrol_default_price_per_hr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcontrol',
            name='default_price_per_hr',
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='default_price_per_kg',
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='eur_price_per_hr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='EUR price for local land routes per Hour', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='eur_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='EUR price for international routes per KG', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='ghs_price_per_hr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GHS price for local land routes per Hour', max_digits=10),
        ),
        migrations.AddField(
            model_name='systemcontrol',
            name='ghs_price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GHS price for international routes per KG', max_digits=10),
        ),
    ]
