# Generated by Django 6.0.1 on 2026-04-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0012_remove_systemcontrol_default_price_per_hr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemcontrol',
            old_name='eur_price_per_hr',
            new_name='eur_price_per_km',
        ),
        migrations.RenameField(
            model_name='systemcontrol',
            old_name='ghs_price_per_hr',
            new_name='ghs_price_per_km',
        ),
    ]
