# Generated by Django 6.0.1 on 2026-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0013_rename_eur_price_per_hr_systemcontrol_eur_price_per_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='estimated_hours',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated road distance in KM', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per KG or per KM', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemcontrol',
            name='eur_price_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='EUR price for local land routes per KM', max_digits=10),
        ),
        migrations.AlterField(
            model_name='systemcontrol',
            name='ghs_price_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='GHS price for local land routes per KM', max_digits=10),
        ),
    ]
