# Generated by Django 6.0.1 on 2026-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0014_remove_shipment_estimated_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Locked-in final price', max_digits=12),
        ),
    ]
