# Generated by Django 6.0.1 on 2026-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0015_shipment_total_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='travel_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Duration of travel for local deliveries', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per KG or per KM/Hour', max_digits=10),
        ),
    ]
