# Generated by Django 6.0.1 on 2026-04-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0016_shipment_travel_hours_alter_shipment_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='destination_address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='origin_address',
        ),
    ]
