# Generated by Django 6.0.1 on 2026-04-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0018_shipment_destination_lat_shipment_destination_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, help_text='Admin-controlled arrival time', null=True),
        ),
    ]
