# Generated by Django 6.0.1 on 2026-04-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0019_alter_shipment_estimated_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
