# Generated by Django 6.0.1 on 2026-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0020_shipment_sender_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='systemcontrol',
            name='use_auto_rates',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Request Received'), ('RECEIVED', 'Received in Warehouse'), ('SORTING', 'Sorting & Packaging'), ('DEPARTED', 'Departed Origin'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED_DEST', 'Arrived at Destination'), ('CLEARING', 'Customs Clearing'), ('READY', 'Ready for Collection'), ('DELIVERED', 'Delivered to Recipient'), ('CANCELLED', 'Order Cancelled')], default='PENDING', max_length=20),
        ),
    ]
